CREATE TYPE node_type_enum AS ENUM ('Root', 'Branch', 'ImageLeaf');

CREATE TABLE tree_nodes (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    parent_id UUID REFERENCES tree_nodes(id) ON DELETE CASCADE,
    node_type node_type_enum NOT NULL,
    -- autogenerated for ImageLeaf as from_updated(updated_at)
    name TEXT NULL,
    -- JSONB for flexible data storage
    data JSONB NOT NULL,
    -- Materialized path for efficient tree queries
    path TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    
);

CREATE INDEX idx_tree_nodes_parent_id ON tree_nodes(parent_id);
CREATE INDEX idx_tree_nodes_path ON tree_nodes USING BTREE(path);
CREATE INDEX idx_tree_nodes_type ON tree_nodes(node_type);
CREATE INDEX idx_tree_nodes_data_gin ON tree_nodes USING GIN(data);

CREATE TABLE node_access
(
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    user_id TEXT NOT NULL ,
    node_id UUID NOT NULL REFERENCES tree_nodes(id) ON DELETE CASCADE
);

CREATE INDEX idx_node_access_user_id ON node_access(user_id);
-- ============================================================================
-- Image Descriptions Cache
-- ============================================================================
CREATE TABLE image_descriptions (
    id UUID PRIMARY KEY DEFAULT uuidv7(), -- uuid_generate_v4(),
    node_id UUID NOT NULL REFERENCES tree_nodes(id) ON DELETE CASCADE,
    model_name TEXT NOT NULL,
    prompt TEXT NOT NULL,
    description TEXT NOT NULL,
    confidence FLOAT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    UNIQUE(node_id, model_name, prompt)
);

CREATE INDEX idx_image_descriptions_node_id ON image_descriptions(node_id);




-- Function to update materialized path on insert/update
CREATE OR REPLACE FUNCTION update_tree_path()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.parent_id IS NULL THEN
        NEW.path := NEW.id::TEXT;
    ELSE
        SELECT path || '.' || NEW.id::TEXT INTO NEW.path
        FROM tree_nodes
        WHERE id = NEW.parent_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tree_nodes_path_trigger
    BEFORE INSERT OR UPDATE ON tree_nodes
    FOR EACH ROW
    EXECUTE FUNCTION update_tree_path();

-- Function to prevent circular references
CREATE OR REPLACE FUNCTION prevent_circular_tree()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.parent_id IS NOT NULL THEN
        IF EXISTS (
            SELECT 1 FROM tree_nodes
            WHERE id = NEW.parent_id
            AND path LIKE NEW.id::TEXT || '%'
        ) THEN
            RAISE EXCEPTION 'Circular reference detected';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tree_nodes_circular_check
    BEFORE INSERT OR UPDATE ON tree_nodes
    FOR EACH ROW
    EXECUTE FUNCTION prevent_circular_tree();


